### ISSUE TITLE
Unable to open the UI

### ISSUE THREAD

**Issue by jjhesk** [jaimervq/all_nodes#62]
```
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.

Traceback (most recent call last):
  File "/..../galsupports/main.py", line 109, in <module>
    main()
  File "/...5/galsupports/main.py", line 101, in main
    launch_gui()
  File "/Use...orts/main.py", line 34, in launch_gui
    AllNodesWindow()
  File "/...orts/all_nodes/graphic/widgets/main_window.py", line 86, in __init__
    self.create_dock_windows()
  File "/Use...orts/all_nodes/graphic/widgets/main_window.py", line 199, in create_dock_windows
    self.attr_editr_dock.setAllowedAreas(
TypeError: 'PySide2.QtCore.Qt.DockWidgetArea' object cannot be interpreted as an integer

**Comment by jaimervq** [comment]
Hi @jjhesk , thanks for raising this.
What OS are you using?

**Comment by jaimervq** [comment]
Hi @jjhesk , could you provide more info about this problem (the os you are using, python version... )
Thanks!

**Comment by jaimervq** [comment]
Closed due to lack of additional info
